version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
